class TournamentSeedData {
  static const List<Map<String, dynamic>> standings = [
    // ─── VOLEIBOL ────────────────────────────────────────────────────────────
    {
      'posicion': 1,
      'equipo': 'Dragones Volley',
      'partidos_jugados': 5,
      'ganados': 4,
      'empatados': 1,
      'perdidos': 0,
      'goles_favor': 15,
      'goles_contra': 4,
      'puntos': 13,
      'color': 0xFF00E5FF, // Cyan
      'disciplina': 'voleibol',
    },
    {
      'posicion': 2,
      'equipo': 'Tiburones AVP',
      'partidos_jugados': 5,
      'ganados': 3,
      'empatados': 2,
      'perdidos': 0,
      'goles_favor': 12,
      'goles_contra': 6,
      'puntos': 11,
      'color': 0xFF00BFA5, // Teal
      'disciplina': 'voleibol',
    },
    {
      'posicion': 3,
      'equipo': 'Fénix Club',
      'partidos_jugados': 5,
      'ganados': 2,
      'empatados': 2,
      'perdidos': 1,
      'goles_favor': 9,
      'goles_contra': 7,
      'puntos': 8,
      'color': 0xFFFFD700, // Gold
      'disciplina': 'voleibol',
    },
    {
      'posicion': 4,
      'equipo': 'Espartanos Volley',
      'partidos_jugados': 5,
      'ganados': 1,
      'empatados': 2,
      'perdidos': 2,
      'goles_favor': 7,
      'goles_contra': 9,
      'puntos': 5,
      'color': 0xFFFF5252, // Coral/Red
      'disciplina': 'voleibol',
    },
    {
      'posicion': 5,
      'equipo': 'Gatos Negros AVP',
      'partidos_jugados': 5,
      'ganados': 1,
      'empatados': 1,
      'perdidos': 3,
      'goles_favor': 6,
      'goles_contra': 11,
      'puntos': 4,
      'color': 0xFF9E9E9E, // Grey
      'disciplina': 'voleibol',
    },
    {
      'posicion': 6,
      'equipo': 'Panteras AVP',
      'partidos_jugados': 5,
      'ganados': 0,
      'empatados': 0,
      'perdidos': 5,
      'goles_favor': 3,
      'goles_contra': 16,
      'puntos': 0,
      'color': 0xFFE040FB, // Magenta
      'disciplina': 'voleibol',
    },

    // ─── BÁSQUETBOL ──────────────────────────────────────────────────────────
    {
      'posicion': 1,
      'equipo': 'Búfalos Basket',
      'partidos_jugados': 4,
      'ganados': 4,
      'empatados': 0,
      'perdidos': 0,
      'goles_favor': 320,
      'goles_contra': 260,
      'puntos': 12,
      'color': 0xFFFFAB00, // Amber/Orange
      'disciplina': 'basquetbol',
    },
    {
      'posicion': 2,
      'equipo': 'Halcones AVP',
      'partidos_jugados': 4,
      'ganados': 2,
      'empatados': 0,
      'perdidos': 2,
      'goles_favor': 280,
      'goles_contra': 290,
      'puntos': 6,
      'color': 0xFF2979FF, // Royal Blue
      'disciplina': 'basquetbol',
    },
    {
      'posicion': 3,
      'equipo': 'Guerreros AVP',
      'partidos_jugados': 4,
      'ganados': 0,
      'empatados': 0,
      'perdidos': 4,
      'goles_favor': 240,
      'goles_contra': 290,
      'puntos': 0,
      'color': 0xFF76FF03, // Lime Green
      'disciplina': 'basquetbol',
    },

    // ─── FÚTBOL ──────────────────────────────────────────────────────────────
    {
      'posicion': 1,
      'equipo': 'Galácticos FC',
      'partidos_jugados': 3,
      'ganados': 2,
      'empatados': 1,
      'perdidos': 0,
      'goles_favor': 8,
      'goles_contra': 3,
      'puntos': 7,
      'color': 0xFFFFE57F, // Light Gold
      'disciplina': 'futbol',
    },
    {
      'posicion': 2,
      'equipo': 'Deportivo AVP',
      'partidos_jugados': 3,
      'ganados': 1,
      'empatados': 1,
      'perdidos': 1,
      'goles_favor': 4,
      'goles_contra': 4,
      'puntos': 4,
      'color': 0xFFD500F9, // Deep Purple
      'disciplina': 'futbol',
    },
    {
      'posicion': 3,
      'equipo': 'Titanes FC',
      'partidos_jugados': 3,
      'ganados': 0,
      'empatados': 0,
      'perdidos': 3,
      'goles_favor': 1,
      'goles_contra': 6,
      'puntos': 0,
      'color': 0xFFFF3D00, // Deep Orange
      'disciplina': 'futbol',
    },
  ];

  static const List<Map<String, dynamic>> matches = [
    // ─── VOLEIBOL ────────────────────────────────────────────────────────────
    {
      'jornada': 'Jornada 1',
      'fecha': '2026-05-10',
      'hora': '10:00',
      'cancha': 'Cancha Central Principal',
      'local': 'Dragones Volley',
      'visitante': 'Panteras AVP',
      'goles_local': 4,
      'goles_visitante': 0,
      'estado': 'FINALIZADO',
      'disciplina': 'voleibol',
    },
    {
      'jornada': 'Jornada 1',
      'fecha': '2026-05-10',
      'hora': '12:00',
      'cancha': 'Cancha Alterna 1',
      'local': 'Tiburones AVP',
      'visitante': 'Gatos Negros AVP',
      'goles_local': 3,
      'goles_visitante': 1,
      'estado': 'FINALIZADO',
      'disciplina': 'voleibol',
    },
    {
      'jornada': 'Jornada 1',
      'fecha': '2026-05-10',
      'hora': '14:00',
      'cancha': 'Cancha Alterna 2',
      'local': 'Fénix Club',
      'visitante': 'Espartanos Volley',
      'goles_local': 2,
      'goles_visitante': 2,
      'estado': 'FINALIZADO',
      'disciplina': 'voleibol',
    },
    {
      'jornada': 'Jornada 2',
      'fecha': '2026-05-17',
      'hora': '09:00',
      'cancha': 'Cancha Central Principal',
      'local': 'Dragones Volley',
      'visitante': 'Fénix Club',
      'goles_local': 2,
      'goles_visitante': 1,
      'estado': 'FINALIZADO',
      'disciplina': 'voleibol',
    },
    {
      'jornada': 'Jornada 2',
      'fecha': '2026-05-17',
      'hora': '11:00',
      'cancha': 'Cancha Alterna 1',
      'local': 'Tiburones AVP',
      'visitante': 'Espartanos Volley',
      'goles_local': 1,
      'goles_visitante': 1,
      'estado': 'FINALIZADO',
      'disciplina': 'voleibol',
    },
    {
      'jornada': 'Jornada 2',
      'fecha': '2026-05-17',
      'hora': '13:00',
      'cancha': 'Cancha Alterna 2',
      'local': 'Gatos Negros AVP',
      'visitante': 'Panteras AVP',
      'goles_local': 2,
      'goles_visitante': 1,
      'estado': 'FINALIZADO',
      'disciplina': 'voleibol',
    },
    {
      'jornada': 'Jornada 3 (EN VIVO)',
      'fecha': '2026-05-24',
      'hora': '10:00',
      'cancha': 'Cancha Central Principal',
      'local': 'Dragones Volley',
      'visitante': 'Tiburones AVP',
      'goles_local': 2,
      'goles_visitante': 2,
      'estado': 'LIVEMATCH',
      'disciplina': 'voleibol',
    },
    {
      'jornada': 'Jornada 3 (EN VIVO)',
      'fecha': '2026-05-24',
      'hora': '12:00',
      'cancha': 'Cancha Alterna 1',
      'local': 'Fénix Club',
      'visitante': 'Gatos Negros AVP',
      'goles_local': 1,
      'goles_visitante': 0,
      'estado': 'LIVEMATCH',
      'disciplina': 'voleibol',
    },
    {
      'jornada': 'Jornada 3 (EN VIVO)',
      'fecha': '2026-05-24',
      'hora': '14:00',
      'cancha': 'Cancha Alterna 2',
      'local': 'Espartanos Volley',
      'visitante': 'Panteras AVP',
      'goles_local': 0,
      'goles_visitante': 0,
      'estado': 'LIVEMATCH',
      'disciplina': 'voleibol',
    },
    {
      'jornada': 'Jornada 4',
      'fecha': '2026-05-31',
      'hora': '10:00',
      'cancha': 'Cancha Central Principal',
      'local': 'Dragones Volley',
      'visitante': 'Gatos Negros AVP',
      'goles_local': 0,
      'goles_visitante': 0,
      'estado': 'PROGRAMADO',
      'disciplina': 'voleibol',
    },
    {
      'jornada': 'Jornada 4',
      'fecha': '2026-05-31',
      'hora': '12:00',
      'cancha': 'Cancha Alterna 1',
      'local': 'Tiburones AVP',
      'visitante': 'Fénix Club',
      'goles_local': 0,
      'goles_visitante': 0,
      'estado': 'PROGRAMADO',
      'disciplina': 'voleibol',
    },
    {
      'jornada': 'Jornada 4',
      'fecha': '2026-05-31',
      'hora': '14:00',
      'cancha': 'Cancha Alterna 2',
      'local': 'Espartanos Volley',
      'visitante': 'Panteras AVP',
      'goles_local': 0,
      'goles_visitante': 0,
      'estado': 'PROGRAMADO',
      'disciplina': 'voleibol',
    },

    // ─── BÁSQUETBOL ──────────────────────────────────────────────────────────
    {
      'jornada': 'Jornada 1',
      'fecha': '2026-05-09',
      'hora': '18:00',
      'cancha': 'Coliseo Cubierto',
      'local': 'Búfalos Basket',
      'visitante': 'Halcones AVP',
      'goles_local': 85,
      'goles_visitante': 72,
      'estado': 'FINALIZADO',
      'disciplina': 'basquetbol',
    },
    {
      'jornada': 'Jornada 2 (EN VIVO)',
      'fecha': '2026-05-23',
      'hora': '19:00',
      'cancha': 'Coliseo Cubierto',
      'local': 'Búfalos Basket',
      'visitante': 'Guerreros AVP',
      'goles_local': 64,
      'goles_visitante': 60,
      'estado': 'LIVEMATCH',
      'disciplina': 'basquetbol',
    },
    {
      'jornada': 'Jornada 3',
      'fecha': '2026-05-30',
      'hora': '17:00',
      'cancha': 'Coliseo Cubierto',
      'local': 'Halcones AVP',
      'visitante': 'Guerreros AVP',
      'goles_local': 0,
      'goles_visitante': 0,
      'estado': 'PROGRAMADO',
      'disciplina': 'basquetbol',
    },

    // ─── FÚTBOL ──────────────────────────────────────────────────────────────
    {
      'jornada': 'Jornada 1',
      'fecha': '2026-05-08',
      'hora': '16:00',
      'cancha': 'Estadio Principal AVP',
      'local': 'Galácticos FC',
      'visitante': 'Deportivo AVP',
      'goles_local': 3,
      'goles_visitante': 1,
      'estado': 'FINALIZADO',
      'disciplina': 'futbol',
    },
    {
      'jornada': 'Jornada 2 (EN VIVO)',
      'fecha': '2026-05-22',
      'hora': '15:30',
      'cancha': 'Estadio Principal AVP',
      'local': 'Deportivo AVP',
      'visitante': 'Titanes FC',
      'goles_local': 2,
      'goles_visitante': 1,
      'estado': 'LIVEMATCH',
      'disciplina': 'futbol',
    },
    {
      'jornada': 'Jornada 3',
      'fecha': '2026-05-29',
      'hora': '16:30',
      'cancha': 'Estadio Principal AVP',
      'local': 'Galácticos FC',
      'visitante': 'Titanes FC',
      'goles_local': 0,
      'goles_visitante': 0,
      'estado': 'PROGRAMADO',
      'disciplina': 'futbol',
    },
  ];
}
