// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDiE3W_rBDOojmsGS4G29Bk0JR-AeNpK24',
    appId: '1:430589318678:web:151b44a826f62725c88737',
    messagingSenderId: '430589318678',
    projectId: 'omnisport-ai',
    authDomain: 'omnisport-ai.firebaseapp.com',
    storageBucket: 'omnisport-ai.firebasestorage.app',
    measurementId: 'G-QK82VYD8HH',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD1dkg3tNBrFt-a6ztd4avVIOKnm2bO-Ng',
    appId: '1:430589318678:android:f312d1927f646f0dc88737',
    messagingSenderId: '430589318678',
    projectId: 'omnisport-ai',
    storageBucket: 'omnisport-ai.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDNgQ3KFr5XcmUcqg7iWB2KSepmE2IFCYY',
    appId: '1:430589318678:ios:7a6f108a45775047c88737',
    messagingSenderId: '430589318678',
    projectId: 'omnisport-ai',
    storageBucket: 'omnisport-ai.firebasestorage.app',
    iosBundleId: 'com.omnisportai.app',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDNgQ3KFr5XcmUcqg7iWB2KSepmE2IFCYY',
    appId: '1:430589318678:ios:7a6f108a45775047c88737',
    messagingSenderId: '430589318678',
    projectId: 'omnisport-ai',
    storageBucket: 'omnisport-ai.firebasestorage.app',
    iosBundleId: 'com.omnisportai.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDiE3W_rBDOojmsGS4G29Bk0JR-AeNpK24',
    appId: '1:430589318678:web:640ad1a5dd7a5919c88737',
    messagingSenderId: '430589318678',
    projectId: 'omnisport-ai',
    authDomain: 'omnisport-ai.firebaseapp.com',
    storageBucket: 'omnisport-ai.firebasestorage.app',
    measurementId: 'G-EZ4VET8TTW',
  );
}
