import 'package:flutter/material.dart';

class AppLocalizations {
  final Locale locale;

  AppLocalizations(this.locale);

  static AppLocalizations of(BuildContext context) {
    return Localizations.of<AppLocalizations>(context, AppLocalizations)!;
  }

  static const _localizedValues = <String, Map<String, String>>{
    'es': {
      'language_picker_title': 'Selecciona tu idioma',
      'language_picker_es': 'Continuar en Español',
      'language_picker_en': 'Continue in English',
      'onboarding_slide1_title': 'Tu Ficha Técnica Profesional',
      'onboarding_slide1_desc': 'Crea y gestiona tu perfil de atleta con estándares internacionales. Centraliza tus estadísticas y trayectoria.',
      'onboarding_slide2_title': 'Potenciado por IA',
      'onboarding_slide2_desc': 'Recibe análisis personalizados y rutinas de entrenamiento generadas por Inteligencia Artificial (Gemini).',
      'onboarding_slide3_title': 'Tus Datos, Siempre Protegidos',
      'onboarding_slide3_desc': 'Operamos bajo cumplimiento estricto de la LOPDP e ISO 27001. Tu información está cifrada y bajo tu control.',
      'skip': 'Saltar',
      'next': 'Siguiente',
      'start': 'Empezar',
      
      // Login Strings
      'login_error_google': 'Error al ingresar con Google',
      'login_error_google_not_found': 'Cuenta no encontrada o inválida. Por favor, regístrate de nuevo',
      'login_error_apple': 'Error al ingresar con Apple',
      'login_fill_fields': 'Por favor completa todos los campos',
      'login_error_generic': 'Ocurrió un error',
      'login_error_not_found': 'Cuenta no encontrada. Por favor, regístrate de nuevo',
      'login_error_wrong_pass': 'Contraseña incorrecta',
      'login_error_email_used': 'El email ya está en uso',
      'login_error_weak_pass': 'La contraseña es muy débil',
      'login_error_not_allowed': '¡Error! Debes habilitar Email/Password en la consola de Firebase.',
      'login_email_label': 'Correo Electrónico',
      'login_password_label': 'Contraseña',
      'login_terms': 'He leído y acepto los Términos de Uso y Política de Privacidad',
      'login_button': 'Iniciar Sesión',
      'register_button': 'Crear Cuenta',
      'login_or': 'O ingresar con',
      'login_toggle_register': '¿No tienes cuenta? Regístrate',
      'login_toggle_login': '¿Ya tienes cuenta? Ingresa',
    },
    'en': {
      'language_picker_title': 'Select your language',
      'language_picker_es': 'Continuar en Español',
      'language_picker_en': 'Continue in English',
      'onboarding_slide1_title': 'Professional Athlete Profile',
      'onboarding_slide1_desc': 'Centralize your stats and sports career with international standards.',
      'onboarding_slide2_title': 'AI-Powered Performance',
      'onboarding_slide2_desc': 'Receive personalized analysis and training routines generated by Gemini AI.',
      'onboarding_slide3_title': 'Data Protection & Privacy',
      'onboarding_slide3_desc': 'Strict compliance with LOPDP and ISO 27001. Your data is encrypted and under your control.',
      'skip': 'Skip',
      'next': 'Next',
      'start': 'Get Started',
      
      // Login Strings
      'login_error_google': 'Error signing in with Google',
      'login_error_google_not_found': 'Account not found or invalid. Please register again',
      'login_error_apple': 'Error signing in with Apple',
      'login_fill_fields': 'Please fill all the fields',
      'login_error_generic': 'An error occurred',
      'login_error_not_found': 'Account not found. Please register again',
      'login_error_wrong_pass': 'Incorrect password',
      'login_error_email_used': 'Email is already in use',
      'login_error_weak_pass': 'Password is too weak',
      'login_error_not_allowed': 'Error! You must enable Email/Password in Firebase Console.',
      'login_email_label': 'Email Address',
      'login_password_label': 'Password',
      'login_terms': 'I have read and accept the Terms of Use and Privacy Policy',
      'login_button': 'Sign In',
      'register_button': 'Create Account',
      'login_or': 'Or sign in with',
      'login_toggle_register': 'Don\'t have an account? Register',
      'login_toggle_login': 'Already have an account? Sign in',
    },
  };

  String get languagePickerTitle => _localizedValues[locale.languageCode]!['language_picker_title']!;
  String get languagePickerEs => _localizedValues[locale.languageCode]!['language_picker_es']!;
  String get languagePickerEn => _localizedValues[locale.languageCode]!['language_picker_en']!;
  String get onboardingSlide1Title => _localizedValues[locale.languageCode]!['onboarding_slide1_title']!;
  String get onboardingSlide1Desc => _localizedValues[locale.languageCode]!['onboarding_slide1_desc']!;
  String get onboardingSlide2Title => _localizedValues[locale.languageCode]!['onboarding_slide2_title']!;
  String get onboardingSlide2Desc => _localizedValues[locale.languageCode]!['onboarding_slide2_desc']!;
  String get onboardingSlide3Title => _localizedValues[locale.languageCode]!['onboarding_slide3_title']!;
  String get onboardingSlide3Desc => _localizedValues[locale.languageCode]!['onboarding_slide3_desc']!;
  String get skip => _localizedValues[locale.languageCode]!['skip']!;
  String get next => _localizedValues[locale.languageCode]!['next']!;
  String get start => _localizedValues[locale.languageCode]!['start']!;
  
  String get loginErrorGoogle => _localizedValues[locale.languageCode]!['login_error_google']!;
  String get loginErrorGoogleNotFound => _localizedValues[locale.languageCode]!['login_error_google_not_found']!;
  String get loginErrorApple => _localizedValues[locale.languageCode]!['login_error_apple']!;
  String get loginFillFields => _localizedValues[locale.languageCode]!['login_fill_fields']!;
  String get loginErrorGeneric => _localizedValues[locale.languageCode]!['login_error_generic']!;
  String get loginErrorNotFound => _localizedValues[locale.languageCode]!['login_error_not_found']!;
  String get loginErrorWrongPass => _localizedValues[locale.languageCode]!['login_error_wrong_pass']!;
  String get loginErrorEmailUsed => _localizedValues[locale.languageCode]!['login_error_email_used']!;
  String get loginErrorWeakPass => _localizedValues[locale.languageCode]!['login_error_weak_pass']!;
  String get loginErrorNotAllowed => _localizedValues[locale.languageCode]!['login_error_not_allowed']!;
  String get loginEmailLabel => _localizedValues[locale.languageCode]!['login_email_label']!;
  String get loginPasswordLabel => _localizedValues[locale.languageCode]!['login_password_label']!;
  String get loginTerms => _localizedValues[locale.languageCode]!['login_terms']!;
  String get loginButton => _localizedValues[locale.languageCode]!['login_button']!;
  String get registerButton => _localizedValues[locale.languageCode]!['register_button']!;
  String get loginOr => _localizedValues[locale.languageCode]!['login_or']!;
  String get loginToggleRegister => _localizedValues[locale.languageCode]!['login_toggle_register']!;
  String get loginToggleLogin => _localizedValues[locale.languageCode]!['login_toggle_login']!;
}

class AppLocalizationsDelegate extends LocalizationsDelegate<AppLocalizations> {
  const AppLocalizationsDelegate();

  @override
  bool isSupported(Locale locale) => ['en', 'es'].contains(locale.languageCode);

  @override
  Future<AppLocalizations> load(Locale locale) async {
    return AppLocalizations(locale);
  }

  @override
  bool shouldReload(AppLocalizationsDelegate old) => false;
}
