import 'package:flutter/material.dart';

class AppLocalizations {
  final Locale locale;

  AppLocalizations(this.locale);

  static AppLocalizations of(BuildContext context) {
    return Localizations.of<AppLocalizations>(context, AppLocalizations)!;
  }

  static const _localizedValues = <String, Map<String, String>>{
    'es': {
      'language_picker_title': 'Selecciona tu idioma',
      'language_picker_es': 'Continuar en Español',
      'language_picker_en': 'Continue in English',
      'onboarding_slide1_title': 'Tu Ficha Técnica Profesional',
      'onboarding_slide1_desc': 'Crea y gestiona tu perfil de atleta con estándares internacionales. Centraliza tus estadísticas y trayectoria.',
      'onboarding_slide2_title': 'Potenciado por IA',
      'onboarding_slide2_desc': 'Recibe análisis personalizados y rutinas de entrenamiento generadas por Inteligencia Artificial (Gemini).',
      'onboarding_slide3_title': 'Tus Datos, Siempre Protegidos',
      'onboarding_slide3_desc': 'Operamos bajo cumplimiento estricto de la LOPDP e ISO 27001. Tu información está cifrada y bajo tu control.',
      'skip': 'Saltar',
      'next': 'Siguiente',
      'start': 'Empezar',
    },
    'en': {
      'language_picker_title': 'Select your language',
      'language_picker_es': 'Continuar en Español',
      'language_picker_en': 'Continue in English',
      'onboarding_slide1_title': 'Professional Athlete Profile',
      'onboarding_slide1_desc': 'Centralize your stats and sports career with international standards.',
      'onboarding_slide2_title': 'AI-Powered Performance',
      'onboarding_slide2_desc': 'Receive personalized analysis and training routines generated by Gemini AI.',
      'onboarding_slide3_title': 'Data Protection & Privacy',
      'onboarding_slide3_desc': 'Strict compliance with LOPDP and ISO 27001. Your data is encrypted and under your control.',
      'skip': 'Skip',
      'next': 'Next',
      'start': 'Get Started',
    },
  };

  String get languagePickerTitle => _localizedValues[locale.languageCode]!['language_picker_title']!;
  String get languagePickerEs => _localizedValues[locale.languageCode]!['language_picker_es']!;
  String get languagePickerEn => _localizedValues[locale.languageCode]!['language_picker_en']!;
  String get onboardingSlide1Title => _localizedValues[locale.languageCode]!['onboarding_slide1_title']!;
  String get onboardingSlide1Desc => _localizedValues[locale.languageCode]!['onboarding_slide1_desc']!;
  String get onboardingSlide2Title => _localizedValues[locale.languageCode]!['onboarding_slide2_title']!;
  String get onboardingSlide2Desc => _localizedValues[locale.languageCode]!['onboarding_slide2_desc']!;
  String get onboardingSlide3Title => _localizedValues[locale.languageCode]!['onboarding_slide3_title']!;
  String get onboardingSlide3Desc => _localizedValues[locale.languageCode]!['onboarding_slide3_desc']!;
  String get skip => _localizedValues[locale.languageCode]!['skip']!;
  String get next => _localizedValues[locale.languageCode]!['next']!;
  String get start => _localizedValues[locale.languageCode]!['start']!;
}

class AppLocalizationsDelegate extends LocalizationsDelegate<AppLocalizations> {
  const AppLocalizationsDelegate();

  @override
  bool isSupported(Locale locale) => ['en', 'es'].contains(locale.languageCode);

  @override
  Future<AppLocalizations> load(Locale locale) async {
    return AppLocalizations(locale);
  }

  @override
  bool shouldReload(AppLocalizationsDelegate old) => false;
}
